# Change these first
owner: faizur11786 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sokos
    url: https://sokos.io
  - name: Dapp Sokos
    url: https://dapp.sokos.io
  - name: Payapp2
    url: https://payapp2.com
  - name: Aqarchain.io
    url: https://aqarchain.io
  - name: Eccb 100
    url: https://eccb100.com
  - name: Payapp2 Link
    url: https://link.payapp2.com
  - name: Console Sokos
    url: https://console.sokos.io
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://cms.smartchain.me/uploads/smartchain_logo_30dc6795ef.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
